### ISSUE TITLE
Unable to disable/enable radio button on the fly by jquery

### ISSUE THREAD

**Issue by faizplus** [timcreative/get-shit-done#1]
After disabling or enabling radio buttons with jquery, the look and feel do not change. Please help

**Comment by alexandru-paduraru** [comment]
Hi,

Thank you for pointing out, we will have it fixed in the next update. Till then you can use this trick to disable:
**$('#optionsRadios2').attr('disabled','true').parent('label').addClass('disabled');**

And this one to enable:
**$('#optionsRadios2').removeAttr('disabled').parent('label').removeClass('disabled');**

It is working also for checkboxes.

All the best,
Alex

**Comment by faizplus** [comment]
thanks! this is working like a charm :+1:
